"""Initial schema

Revision ID: aaf9abdcb332
Revises: 
Create Date: 2026-02-01 18:32:58.827590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaf9abdcb332'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_definitions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('page_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'deprecated')", name='page_definitions_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_key', 'version', name='uq_page_key_version')
    )
    op.create_table('wizard_definitions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('wizard_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'deprecated')", name='wizard_definitions_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wizard_key', 'version', name='uq_wizard_key_version')
    )
    op.create_table('wizard_releases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('wizard_key', sa.Text(), nullable=False),
    sa.Column('release_key', sa.Text(), nullable=False),
    sa.Column('wizard_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wizard_key', 'wizard_version'], ['wizard_definitions.wizard_key', 'wizard_definitions.version'], name='fk_wizard_release_definition'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wizard_key', 'release_key', name='uq_wizard_release_key')
    )
    op.create_table('wizard_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('wizard_key', sa.Text(), nullable=False),
    sa.Column('wizard_version', sa.Text(), nullable=False),
    sa.Column('partner_id', sa.Text(), nullable=True),
    sa.Column('merchant_order_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN (\n                'started',\n                'quoted',\n                'selected',\n                'kyc_passed',\n                'accepted',\n                'paid',\n                'issued',\n                'completed',\n                'failed'\n            )", name='wizard_sessions_status_check'),
    sa.ForeignKeyConstraint(['wizard_key', 'wizard_version'], ['wizard_definitions.wizard_key', 'wizard_definitions.version'], name='fk_session_wizard_definition'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('policy_number', sa.Text(), nullable=False),
    sa.Column('insurer', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['wizard_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quote_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['wizard_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('policies')
    op.drop_table('wizard_sessions')
    op.drop_table('wizard_releases')
    op.drop_table('wizard_definitions')
    op.drop_table('page_definitions')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
