"""make_wizard_session_current_step_nullable_add_expires_at

Revision ID: d0b3ee3b7f4b
Revises: aaf9abdcb332
Create Date: 2026-02-01 21:19:30.758637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b3ee3b7f4b'
down_revision: Union[str, None] = 'aaf9abdcb332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_events_entity'), table_name='audit_events')
    op.drop_index(op.f('idx_page_definitions_key_status'), table_name='page_definitions')
    op.drop_index(op.f('idx_wizard_definitions_key_status'), table_name='wizard_definitions')
    op.add_column('wizard_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('wizard_sessions', 'current_step',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('idx_sessions_partner_order'), table_name='wizard_sessions')
    op.drop_index(op.f('idx_sessions_wizard'), table_name='wizard_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sessions_wizard'), 'wizard_sessions', ['wizard_key', 'wizard_version'], unique=False)
    op.create_index(op.f('idx_sessions_partner_order'), 'wizard_sessions', ['partner_id', 'merchant_order_id'], unique=False)
    op.alter_column('wizard_sessions', 'current_step',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('wizard_sessions', 'expires_at')
    op.create_index(op.f('idx_wizard_definitions_key_status'), 'wizard_definitions', ['wizard_key', 'status'], unique=False)
    op.create_index(op.f('idx_page_definitions_key_status'), 'page_definitions', ['page_key', 'status'], unique=False)
    op.create_index(op.f('idx_audit_events_entity'), 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_events_created_at'), 'audit_events', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
